export const Packages = [
  {
    packageId: "1",
    packageName: "First",
    packageDuration: "1D 1N",
    flightDetails: "HYD-LAX",
    stayDetails: "Hilton Hotel and Resort",
    country: "Los Angeles, USA",
    activities: ["hiking", "surfing", "meals"],
    packagePrice: "250",
  },
  {
    packageId: "2",
    packageName: "Second",
    packageDuration: "1D 2N",
    flightDetails: "AAL-PMV",
    stayDetails: "Casa Ritual",
    country: "Margerita, Venezuela",
    activities: ["hiking", "camping", "meals"],
    packagePrice: "200",
  },
  {
    packageId: "3",
    packageName: "Third",
    packageDuration: "2D 2N",
    flightDetails: "AAR-YXX",
    stayDetails: "Ramada by Wyndham",
    country: "Abbotsford, Canada",
    activities: ["horse ride", "fishing", "meals"],
    packagePrice: "300",
  },

  {
    packageId: "4",
    packageName: "Fourth",
    packageDuration: "2D 3N",
    flightDetails: "AUH-GUM",
    stayDetails: "Guam Plaza Resort",
    country: "Guam, Guam",
    activities: ["fishing", "surfing", "meals"],
    packagePrice: "300",
  },
  {
    packageId: "5",
    packageName: "Fifth",
    packageDuration: "3D 2N",
    flightDetails: "LEI-NSB",
    stayDetails: "New Smyrna Beach Hotels",
    country: " New Smyrna Beach, USA",
    activities: ["hike", "fishing", "surf", "meals"],
    packagePrice: "400",
  },
  {
    packageId: "6",
    packageName: "Sixth",
    packageDuration: "3D 3N",
    flightDetails: "YAA-CRK",
    stayDetails: "Hilton Clark Sun Valley Resort",
    country: "Angeles, Philippines",
    activities: ["hiking", "meals"],
    packagePrice: "450",
  },
  {
    packageId: "7",
    packageName: "Seventh",
    packageDuration: "4D 3N",
    flightDetails: "TER-NCY",
    stayDetails: "Allobroges Park Hotel",
    country: "New York, USA",
    activities: ["meals"],
    packagePrice: "500",
  },
  {
    packageId: "8",
    packageName: "Eighth",
    packageDuration: "4D 4N",
    flightDetails: "ESB-AAE",
    stayDetails: "Sheraton Annaba Hotel",
    country: "Annaba, Algeria",
    activities: ["hiking", "camping", "surfing", "meals"],
    packagePrice: "600",
  },
  {
    packageId: "9",
    packageName: "Ninth",
    packageDuration: "3D 2N",
    flightDetails: "TNR-EFL",
    stayDetails: "Aenos Hotel",
    country: "Island of Kefalonia, Greece",
    activities: ["hike", "fishing", "meals"],
    packagePrice: "500",
  },
  {
    packageId: "10",
    packageName: "Tenth",
    packageDuration: "2D 3N",
    flightDetails: "TSE-RAR",
    stayDetails: "Little Polynesian Resort",
    country: "Rarotonga, Cook Islands",
    activities: ["hiking", "surfing", "meals"],
    packagePrice: "650",
  },
  {
    packageId: "11",
    packageName: "Eleventh",
    packageDuration: "5D 4N",
    flightDetails: "SDA-GYD",
    stayDetails: "Dreamland Golf Hotel",
    country: "Baku, Azerbaijan",
    activities: ["rafting", "meals"],
    packagePrice: "700",
  },
  {
    packageId: "12",
    packageName: "Twelfth",
    packageDuration: "4D 5N",
    flightDetails: "SOB-ERS",
    stayDetails: "Arebbush Travel Lodge",
    country: "Windhoek, Namibia",
    activities: ["surfing", "meals"],
    packagePrice: "700",
  },
  {
    packageId: "13",
    packageName: "Thirteenth",
    packageDuration: "2D 1N",
    flightDetails: "SXF-CNF",
    stayDetails: "Lagoon Prime Hotel",
    country: "Belo Horizonte, Brazil",
    activities: ["hiking", "meals"],
    packagePrice: "450",
  },
  {
    packageId: "14",
    packageName: "Fourteenth",
    packageDuration: "4D 3N",
    flightDetails: "THF-FMN",
    stayDetails: "Brentwood Inn & Garden",
    country: "Farmington, USA",
    activities: ["meals"],
    packagePrice: "500",
  },
  {
    packageId: "15",
    packageName: "Fifteenth",
    packageDuration: "4D 4N",
    flightDetails: "OXB-FRU",
    stayDetails: "Viva Hotel",
    country: "Bishkek, Kyrgyzstan",
    activities: ["hiking", "meals"],
    packagePrice: "600",
  },
  {
    packageId: "16",
    packageName: "Sixteenth",
    packageDuration: "2D 2N",
    flightDetails: "BME-BHQ",
    stayDetails: "Royal Exchange Hotel",
    country: "Broken Hill, Australia",
    activities: ["hiking", "meals"],
    packagePrice: "800",
  },
  {
    packageId: "17",
    packageName: "Seventeenth",
    packageDuration: "3D 2N",
    flightDetails: "EZE-OTP",
    stayDetails: "Crowne Plaza Bucharest",
    country: "Bucharest, Romania",
    activities: ["meals"],
    packagePrice: "700",
  },
  {
    packageId: "18",
    packageName: "Eighteenth",
    packageDuration: "6D 5N",
    flightDetails: "BTM-PUS",
    stayDetails: "Air Sky Hotel",
    country: "BuSan, South Korea",
    activities: ["hiking", "boating", "meals"],
    packagePrice: "1000",
  },
  {
    packageId: "19",
    packageName: "Nineteenth",
    packageDuration: "5D 5N",
    flightDetails: "YYC-CLO",
    stayDetails: "Hotel Royal Elim Internacional",
    country: "Cali, Colombia",
    activities: ["hiking", "meals"],
    packagePrice: "950",
  },
  {
    packageId: "20",
    packageName: "Twentieth",
    packageDuration: "7D 6N",
    flightDetails: "CAY-SLU",
    stayDetails: "Villa Beach Cottages",
    country: "Castries, Saint Lucia",
    activities: ["boating", "meals"],
    packagePrice: "1200",
  },
  {
    packageId: "21",
    packageName: "Twentyfirst",
    packageDuration: "6D 7N",
    flightDetails: "MAA-STT",
    stayDetails: "Hotel Calimera",
    country: "St. Thomas, Virgin Islands",
    activities: ["camping", "surfing", "meals"],
    packagePrice: "1050",
  },
  {
    packageId: "22",
    packageName: "Twentysecond",
    packageDuration: "5D 6N",
    flightDetails: "MDW-ORD",
    stayDetails: "Wyndham Chicago O'Hare",
    country: "Chicago, USA",
    activities: ["meals"],
    packagePrice: "1150",
  },
  {
    packageId: "23",
    packageName: "Twentythird",
    packageDuration: "4D 4N",
    flightDetails: "CKG-HTA",
    stayDetails: "Hotel Salzburgo",
    country: "Chita, Russia",
    activities: ["meals"],
    packagePrice: "950",
  },
  {
    packageId: "24",
    packageName: "Twentyfourth",
    packageDuration: "7D 6N",
    flightDetails: "ZSA-DAM",
    stayDetails: "Dana Rayhaan by Rotana",
    country: "Damascus, Saudi Arabien",
    activities: ["meals"],
    packagePrice: "1250",
  },
  {
    packageId: "25",
    packageName: "Twentyfifth",
    packageDuration: "7D 7N",
    flightDetails: "DWD-LGI",
    stayDetails: "Kooters Vacation Rentals",
    country: "New York city, USA",
    activities: ["meals"],
    packagePrice: "1350",
  },
  {
    packageId: "26",
    packageName: "Twentysixth",
    packageDuration: "8D 7N",
    flightDetails: "DOY-YDF",
    stayDetails: "St Christopher's Hotel",
    country: "Deer Lake, Canada",
    activities: ["hiking", "meals"],
    packagePrice: "1400",
  },
  {
    packageId: "27",
    packageName: "Twentyseventh",
    packageDuration: "8D 8N",
    flightDetails: "DUJ-JIB",
    stayDetails: "Atlantic Hotel",
    country: "Balbala, Djibouti",
    activities: ["meals"],
    packagePrice: "1500",
  },
  {
    packageId: "28",
    packageName: "Twentyeighth",
    packageDuration: "5D 5N",
    flightDetails: "DYU-ELS",
    stayDetails: "Premier Hotel Regent",
    country: "East London, South Africa",
    activities: ["boating", "meals"],
    packagePrice: "850",
  },
  {
    packageId: "29",
    packageName: "Twentyninth",
    packageDuration: "7D 6N",
    flightDetails: "EAU-YEG",
    stayDetails: "Chateau Motel",
    country: "Edmonton, Canada",
    activities: ["hiking", "meals"],
    packagePrice: "1550",
  },
  {
    packageId: "30",
    packageName: "Thirtieth",
    packageDuration: "4D 4N",
    flightDetails: "EEK-SVX",
    stayDetails: "Grand Palace Hotel & Spa",
    country: "Yekaterinburg, Russia",
    activities: ["meals"],
    packagePrice: "650",
  },
];
